"""added game model

Revision ID: 1d1940e4bf68
Revises: fbc1915a9978
Create Date: 2025-06-05 06:29:44.982339

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d1940e4bf68"
down_revision: Union[str, None] = "fbc1915a9978"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "season",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("league_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["league.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_season_id"), "season", ["id"], unique=False)
    op.create_index(op.f("ix_season_year"), "season", ["year"], unique=False)
    op.create_table(
        "game",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("game_date", sa.Date(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("home_team_id", sa.Integer(), nullable=False),
        sa.Column("away_team_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_game_id"), "game", ["id"], unique=False)
    op.create_index(op.f("ix_game_year"), "game", ["year"], unique=False)
    op.add_column("team", sa.Column("season_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "team", "season", ["season_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("team_season_id_fkey", "team", type_="foreignkey")
    op.drop_column("team", "season_id")
    op.drop_index(op.f("ix_game_year"), table_name="game")
    op.drop_index(op.f("ix_game_id"), table_name="game")
    op.drop_table("game")
    op.drop_index(op.f("ix_season_year"), table_name="season")
    op.drop_index(op.f("ix_season_id"), table_name="season")
    op.drop_table("season")
    # ### end Alembic commands ###
