"""Initial sports models

Revision ID: 3ff968b8c7a7
Revises:
Create Date: 2025-06-04 21:20:56.928866

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3ff968b8c7a7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "league",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_league_id"), "league", ["id"], unique=False)
    op.create_index(op.f("ix_league_name"), "league", ["name"], unique=False)
    op.create_index(op.f("ix_league_year"), "league", ["year"], unique=False)
    op.create_table(
        "team",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("league_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["league.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_team_id"), "team", ["id"], unique=False)
    op.create_index(op.f("ix_team_year"), "team", ["year"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_team_year"), table_name="team")
    op.drop_index(op.f("ix_team_id"), table_name="team")
    op.drop_table("team")
    op.drop_index(op.f("ix_league_year"), table_name="league")
    op.drop_index(op.f("ix_league_name"), table_name="league")
    op.drop_index(op.f("ix_league_id"), table_name="league")
    op.drop_table("league")
    # ### end Alembic commands ###
