"""drop game model as table

Revision ID: 65ac7951db19
Revises: 1d1940e4bf68
Create Date: 2025-06-06 15:54:36.509188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65ac7951db19'
down_revision: Union[str, None] = '1d1940e4bf68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_id'), table_name='game')
    op.drop_index(op.f('ix_game_year'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('game_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('home_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('away_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.id'], name=op.f('game_away_team_id_fkey')),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.id'], name=op.f('game_home_team_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('game_pkey'))
    )
    op.create_index(op.f('ix_game_year'), 'game', ['year'], unique=False)
    op.create_index(op.f('ix_game_id'), 'game', ['id'], unique=False)
    # ### end Alembic commands ###
