"""initial mlb migration

Revision ID: adc13f0e7dd9
Revises:
Create Date: 2025-06-12 20:14:35.305972

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "adc13f0e7dd9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mlb_boxscore",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("team_1_scoreboard_runs", sa.Integer(), nullable=False),
        sa.Column("team_2_scoreboard_runs", sa.Integer(), nullable=False),
        sa.Column("team_1_scoreboard_hits", sa.Integer(), nullable=False),
        sa.Column("team_2_scoreboard_hits", sa.Integer(), nullable=False),
        sa.Column("team_1_scoreboard_errors", sa.Integer(), nullable=False),
        sa.Column("team_2_scoreboard_errors", sa.Integer(), nullable=False),
        sa.Column("team_1_hitting_at_bats", sa.Integer(), nullable=False),
        sa.Column("team_2_hitting_at_bats", sa.Integer(), nullable=False),
        sa.Column("team_1_hitting_runs", sa.Integer(), nullable=False),
        sa.Column("team_2_hitting_runs", sa.Integer(), nullable=False),
        sa.Column("team_1_hitting_hits", sa.Integer(), nullable=False),
        sa.Column("team_2_hitting_hits", sa.Integer(), nullable=False),
        sa.Column("team_1_hitting_runs_batted_in", sa.Integer(), nullable=False),
        sa.Column("team_2_hitting_runs_batted_in", sa.Integer(), nullable=False),
        sa.Column("team_1_hitting_home_runs", sa.Integer(), nullable=False),
        sa.Column("team_2_hitting_home_runs", sa.Integer(), nullable=False),
        sa.Column("team_1_hitting_base_on_balls", sa.Integer(), nullable=False),
        sa.Column("team_2_hitting_base_on_balls", sa.Integer(), nullable=False),
        sa.Column("team_1_hitting_strikeouts", sa.Integer(), nullable=False),
        sa.Column("team_2_hitting_strikeouts", sa.Integer(), nullable=False),
        sa.Column("team_1_fielding_errors", sa.Integer(), nullable=False),
        sa.Column("team_2_fielding_errors", sa.Integer(), nullable=False),
        sa.Column("team_1_pitching_innings_pitched", sa.Float(), nullable=False),
        sa.Column("team_2_pitching_innings_pitched", sa.Float(), nullable=False),
        sa.Column("team_1_pitching_hits", sa.Integer(), nullable=False),
        sa.Column("team_2_pitching_hits", sa.Integer(), nullable=False),
        sa.Column("team_1_pitching_runs", sa.Integer(), nullable=False),
        sa.Column("team_2_pitching_runs", sa.Integer(), nullable=False),
        sa.Column("team_1_pitching_earned_runs", sa.Integer(), nullable=False),
        sa.Column("team_2_pitching_earned_runs", sa.Integer(), nullable=False),
        sa.Column("team_1_pitching_walks", sa.Integer(), nullable=False),
        sa.Column("team_2_pitching_walks", sa.Integer(), nullable=False),
        sa.Column("team_1_pitching_strikeouts", sa.Integer(), nullable=False),
        sa.Column("team_2_pitching_strikeouts", sa.Integer(), nullable=False),
        sa.Column("team_1_pitching_home_runs", sa.Integer(), nullable=False),
        sa.Column("team_2_pitching_home_runs", sa.Integer(), nullable=False),
        sa.Column("team_1_pitching_pitches_thrown", sa.String(), nullable=False),
        sa.Column("team_2_pitching_pitches_thrown", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mlb_boxscore_id"), "mlb_boxscore", ["id"], unique=False)
    op.create_table(
        "mlb_game",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("game_date", sa.Date(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mlb_game_id"), "mlb_game", ["id"], unique=False)
    op.create_index(op.f("ix_mlb_game_year"), "mlb_game", ["year"], unique=False)
    op.create_table(
        "mlb_league",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mlb_league_id"), "mlb_league", ["id"], unique=False)
    op.create_index(op.f("ix_mlb_league_name"), "mlb_league", ["name"], unique=False)
    op.create_index(op.f("ix_mlb_league_year"), "mlb_league", ["year"], unique=False)
    op.create_table(
        "mlb_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("record_date", sa.Date(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("home_wins", sa.Integer(), nullable=False),
        sa.Column("away_wins", sa.Integer(), nullable=False),
        sa.Column("home_losses", sa.Integer(), nullable=False),
        sa.Column("away_losses", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mlb_record_id"), "mlb_record", ["id"], unique=False)
    op.create_index(op.f("ix_mlb_record_year"), "mlb_record", ["year"], unique=False)
    op.create_table(
        "mlb_season",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mlb_season_id"), "mlb_season", ["id"], unique=False)
    op.create_index(op.f("ix_mlb_season_year"), "mlb_season", ["year"], unique=False)
    op.create_table(
        "mlb_team",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mlb_team_id"), "mlb_team", ["id"], unique=False)
    op.create_index(op.f("ix_mlb_team_year"), "mlb_team", ["year"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mlb_team_year"), table_name="mlb_team")
    op.drop_index(op.f("ix_mlb_team_id"), table_name="mlb_team")
    op.drop_table("mlb_team")
    op.drop_index(op.f("ix_mlb_season_year"), table_name="mlb_season")
    op.drop_index(op.f("ix_mlb_season_id"), table_name="mlb_season")
    op.drop_table("mlb_season")
    op.drop_index(op.f("ix_mlb_record_year"), table_name="mlb_record")
    op.drop_index(op.f("ix_mlb_record_id"), table_name="mlb_record")
    op.drop_table("mlb_record")
    op.drop_index(op.f("ix_mlb_league_year"), table_name="mlb_league")
    op.drop_index(op.f("ix_mlb_league_name"), table_name="mlb_league")
    op.drop_index(op.f("ix_mlb_league_id"), table_name="mlb_league")
    op.drop_table("mlb_league")
    op.drop_index(op.f("ix_mlb_game_year"), table_name="mlb_game")
    op.drop_index(op.f("ix_mlb_game_id"), table_name="mlb_game")
    op.drop_table("mlb_game")
    op.drop_index(op.f("ix_mlb_boxscore_id"), table_name="mlb_boxscore")
    op.drop_table("mlb_boxscore")
    # ### end Alembic commands ###
