"""added table associations

Revision ID: afac9f468e25
Revises: adc13f0e7dd9
Create Date: 2025-06-12 20:32:43.970672

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "afac9f468e25"
down_revision: Union[str, None] = "adc13f0e7dd9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mlb_team_season_link",
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["season_id"], ["mlb_season.id"], name="fk_team_season_link_season_id"
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["mlb_team.id"], name="fk_team_season_link_team_id"
        ),
        sa.PrimaryKeyConstraint("team_id", "season_id"),
    )
    op.add_column("mlb_boxscore", sa.Column("team_1_id", sa.Integer(), nullable=False))
    op.add_column("mlb_boxscore", sa.Column("team_2_id", sa.Integer(), nullable=False))
    op.add_column("mlb_boxscore", sa.Column("mlb_game_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_mlb_boxscore_team_1_id", "mlb_boxscore", "mlb_team", ["team_1_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_mlb_boxscore_team_2_id", "mlb_boxscore", "mlb_team", ["team_2_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_mlb_boxscore_mlb_game_id",
        "mlb_boxscore",
        "mlb_game",
        ["mlb_game_id"],
        ["id"],
    )
    op.add_column("mlb_game", sa.Column("boxscore_id", sa.Integer(), nullable=True))
    op.add_column("mlb_game", sa.Column("home_team_id", sa.Integer(), nullable=False))
    op.add_column("mlb_game", sa.Column("away_team_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "fk_mlb_game_boxscore_id", "mlb_game", "mlb_boxscore", ["boxscore_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_mlb_game_home_team_id", "mlb_game", "mlb_team", ["home_team_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_mlb_game_away_team_id", "mlb_game", "mlb_team", ["away_team_id"], ["id"]
    )
    op.add_column("mlb_record", sa.Column("team_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "fk_mlb_record_mlb_team_id", "mlb_record", "mlb_team", ["team_id"], ["id"]
    )
    op.add_column("mlb_season", sa.Column("league_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "fk_mlb_season_league_id", "mlb_season", "mlb_league", ["league_id"], ["id"]
    )
    op.add_column("mlb_team", sa.Column("league_id", sa.Integer(), nullable=False))
    op.add_column("mlb_team", sa.Column("season_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "fk_mlb_team_league_id", "mlb_team", "mlb_league", ["league_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_mlb_team_season_id", "mlb_team", "mlb_season", ["season_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_mlb_team_season_id", "mlb_team", type_="foreignkey")
    op.drop_constraint("fk_mlb_team_league_id", "mlb_team", type_="foreignkey")
    op.drop_column("mlb_team", "season_id")
    op.drop_column("mlb_team", "league_id")
    op.drop_constraint("fk_mlb_season_league_id", "mlb_season", type_="foreignkey")
    op.drop_column("mlb_season", "league_id")
    op.drop_constraint("fk_mlb_record_mlb_team_id", "mlb_record", type_="foreignkey")
    op.drop_column("mlb_record", "team_id")
    op.drop_constraint("fk_mlb_game_away_team_id", "mlb_game", type_="foreignkey")
    op.drop_constraint("fk_mlb_game_home_team_id", "mlb_game", type_="foreignkey")
    op.drop_constraint("fk_mlb_game_boxscore_id", "mlb_game", type_="foreignkey")
    op.drop_column("mlb_game", "away_team_id")
    op.drop_column("mlb_game", "home_team_id")
    op.drop_column("mlb_game", "boxscore_id")
    op.drop_constraint(
        "fk_mlb_boxscore_mlb_game_id", "mlb_boxscore", type_="foreignkey"
    )
    op.drop_constraint("fk_mlb_boxscore_team_2_id", "mlb_boxscore", type_="foreignkey")
    op.drop_constraint("fk_mlb_boxscore_team_1_id", "mlb_boxscore", type_="foreignkey")
    op.drop_column("mlb_boxscore", "mlb_game_id")
    op.drop_column("mlb_boxscore", "team_2_id")
    op.drop_column("mlb_boxscore", "team_1_id")
    op.drop_table("mlb_team_season_link")
    # ### end Alembic commands ###
