"""added record model

Revision ID: fbc1915a9978
Revises: 3ff968b8c7a7
Create Date: 2025-06-05 05:55:43.685154

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fbc1915a9978"
down_revision: Union[str, None] = "3ff968b8c7a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("record_date", sa.Date(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("home_wins", sa.Integer(), nullable=False),
        sa.Column("away_wins", sa.Integer(), nullable=False),
        sa.Column("home_losses", sa.Integer(), nullable=False),
        sa.Column("away_losses", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_record_id"), "record", ["id"], unique=False)
    op.create_index(op.f("ix_record_year"), "record", ["year"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_record_year"), table_name="record")
    op.drop_index(op.f("ix_record_id"), table_name="record")
    op.drop_table("record")
    # ### end Alembic commands ###
